# -*- coding: utf-8 -*-
"""Autoencoder_denoising.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mlThipfLavU67652miehGO8GxZ2LNTCd
"""

import numpy as np
import soundfile as sf
import torch.nn as nn
import torch, copy
from torchsummary import summary

# in testing, I coudld get decent-ish results with 30 dictionary atoms
# so here, I'll try and narrow it down to 64

# so here's a downsampling block
class DownBlock(nn.Module):
  def __init__(self, in_channels, out_channels):
    super().__init__()
    self.conv = nn.Sequential(
        nn.Conv1d(in_channels, out_channels, kernel_size = 3, padding = 1),
        nn.ReLU(),
        nn.Conv1d(out_channels, out_channels, kernel_size = 3, padding = 1),
        nn.ReLU()
    )
    # this is where we halve input length
    self.pool = nn.MaxPool1d(kernel_size=2, stride=2)
  def forward(self, x):
    x = self.conv(x)
    skip = x.clone()
    x = self.pool(x)
    return x, skip

# PRIMO VICTORIA: we have an autoencoder that works, now let's come up with some data for it
class UNet_Autoencoder(nn.Module):
  def __init__(self, in_channels, out_channels):
    super().__init__()
    self.down1 = DownBlock(in_channels, 32)
    self.down2 = DownBlock(32, 64)

    self.bottleneck = nn.Sequential(
        nn.Conv1d(64, 128, kernel_size=3, padding=1),
        nn.ReLU(),
        nn.Conv1d(128, 128, kernel_size=3, padding=1),
        nn.ReLU()
    )

    self.final_layer = nn.Conv1d(32, 1, kernel_size=1)
  def forward(self, x):
    x, skip1 = self.down1(x)
    x, skip2 = self.down2(x)
    x = self.bottleneck(x)

    x = nn.ConvTranspose1d(128, 64, kernel_size=2, stride=2)(x)
    x = torch.cat([skip2, x], dim=1)
    x = nn.Conv1d(128, 64, kernel_size=3, padding=1)(x)

    x = nn.ConvTranspose1d(64, 32, kernel_size=2, stride=2)(x)
    x = torch.cat([skip1, x], dim=1)
    x = nn.Conv1d(64, 32, kernel_size=3, padding=1)(x)

    x = self.final_layer(x)

    return x

model = UNet_Autoencoder(1, 1)
input = torch.randn(1, 1, 4096)
output = model(input)
print(output.shape)